<div class="container py-20">
<h1 class="font-28 color-blue2">AVISO LEGAL Y CONDICIONES DE USO</h1>

    <div class="bg-white rounded p-20">
        <p><em>Documento revisado el 29/10/2019</em></p>
<p>En cumplimiento del art&iacute;culo 10 de la Ley 34/2002, de 11 de julio, de Servicios de la Sociedad de la Informaci&oacute;n y del Comercio Electr&oacute;nico (LSSICE), Aitor Rosales N&uacute;&ntilde;ez (en adelante, &ldquo;Soydechollos&rdquo;), Responsable de esta web, pone a disposici&oacute;n de los Usuarios la presente informaci&oacute;n, para definir sus Condiciones de Uso.</p>
<p>Adicionalmente a los contenidos aqu&iacute; expuestos, los aspectos espec&iacute;ficos relacionados con la protecci&oacute;n de los datos personales y la privacidad de los usuarios de esta web se desarrollan en las p&aacute;ginas de Pol&iacute;tica de Privacidad y Pol&iacute;tica de Cookies.</p>
<p><strong>1. DATOS IDENTIFICATIVOS</strong></p>
<p>A continuaci&oacute;n se reflejan los datos de informaci&oacute;n general del Sitio Web https://soydechollos.com/. El titular del dominio web es Aitor Rosales N&uacute;&ntilde;ez, en adelante &laquo;Soydechollos&raquo;, con domicilio a estos efectos en R&uacute;a Coru&ntilde;a 76 9&ordm;D, Vigo (Espa&ntilde;a) con NIF: 53191490B. Tel&eacute;fono de contacto: 625293513. Correo electr&oacute;nico de contacto: contacto[arroba]soydechollos.com</p>
<p><strong>2. T&Eacute;RMINOS Y CONDICIONES DE USO DE LA WEB</strong></p>
<p>&laquo;Soydechollos&raquo;, responsable del sitio web, pone a disposici&oacute;n de los usuarios el presente documento con el que pretende dar cumplimiento a las obligaciones dispuestas en la Ley 34/2002, de Servicios de la Sociedad de la Informaci&oacute;n y del Comercio Electr&oacute;nico (LSSI-CE), as&iacute; como informar a todos los usuarios del sitio web respecto a cu&aacute;les son las condiciones de uso del mismo.</p>
<p>Toda persona que acceda a este sitio web asume el papel de USUARIO, comprometi&eacute;ndose a la observancia y cumplimiento riguroso de las disposiciones aqu&iacute; dispuestas, as&iacute; como a cualesquiera otra disposici&oacute;n legal que fuera de aplicaci&oacute;n.</p>
<p>&ldquo;Soydechollos&rdquo; se reserva el derecho a modificar cualquier tipo de informaci&oacute;n que pudiera aparecer en el sitio web, sin que exista obligaci&oacute;n de preavisar o poner en conocimiento de los usuarios dichas obligaciones, entendi&eacute;ndose como suficiente con la publicaci&oacute;n en el sitio web.</p>
<p><strong>2.1. Finalidad de este Sitio Web</strong></p>
<p>La web https://soydechollos.com/ es un blog que tiene como finalidad ofrecer informaci&oacute;n para conseguir productos o servicios de calidad al mejor precio. Como consumidores online durante m&aacute;s de una d&eacute;cada, queremos transmitir a todos los usuarios nuestra experiencia comprando por Internet de forma segura y, sobre todo, econ&oacute;mica.</p>
<p>Soydechollos no comercializa ning&uacute;n producto ni servicio; simplemente es un espacio donde se difunden ofertas de terceros a los usuarios de la web. Por consiguiente, la compra de cualquier producto o servicio vendido por un vendedor externo, concierne &uacute;nica y exclusivamente al comprador y al vendedor de dicho producto, as&iacute; como el cumplimiento de las obligaciones legales derivadas del mismo.</p>
<p>&iquest;Qu&eacute; encontrar&aacute;s en la Web?</p>
<ul class="conVinetas">
<li>Posts sobre productos o servicios que hemos encontrado a&nbsp;un precio rebajado, vendidos por una tienda online 100% de confianza y con reputaci&oacute;n.</li>
<li>Avisos de ofertas, gangas, descuentos&nbsp;y&nbsp;promociones de empresas conocidas que pueden ser realmente interesante para los usuarios.</li>
<li>Tutoriales de compra, consejos e informaci&oacute;n de calidad para comprar de forma segura.</li>
<li>Reviews de productos.</li>
</ul>
<p>&iquest;Qu&eacute; NO encontrar&aacute;s en este blog?</p>
<ul class="conVinetas">
<li>Referencias a productos subastados.</li>
<li>Referencias a ventas de segunda mano por parte de particulares.</li>
<li>Publicidad enga&ntilde;osa.</li>
<li>SPAM, lo odiamos tanto como t&uacute;.</li>
</ul>
<p><strong>2.2. Condiciones de Uso del Sitio Web</strong></p>
<p>Como Usuario, te obligas expresamente a acceder y utilizar el Sitio Web de una forma diligente y correcta, respetando las siguientes normas y asumiendo cualquier responsabilidad que pudiera derivarse del incumplimiento de las mismas.</p>
<ol type="a">
<li>El acceso a la Web es libre y gratuito. No es necesario registrarse en la web, ni facilitar ning&uacute;n tipo de dato personal, para navegar por la misma. No obstante, &laquo;Soydechollos&raquo; se reserva el derecho de que para poder acceder a determinados servicios o contenido tengas que registrarte a trav&eacute;s de la plataforma.</li>
<li>El mero acceso a este Sitio Web no supone entablar ning&uacute;n tipo de relaci&oacute;n de car&aacute;cter comercial entre &laquo;Soydechollos&raquo; y el Usuario.</li>
<li>El uso de esta web est&aacute; dirigido a personas mayores de edad.</li>
<li>&ldquo;Soydechollos&rdquo; podr&aacute; modificar el contenido de la web en cualquier momento y sin previo aviso.</li>
<li>&ldquo;Soydechollos&rdquo; pone a disposici&oacute;n del Usuario enlaces u otros elementos que permiten el acceso hacia otros sitios web pertenecientes a terceros. No comercializamos los productos y servicios de dichas p&aacute;ginas enlazadas, ni asumimos ning&uacute;n tipo de responsabilidad sobre las mismas, ni sobre la informaci&oacute;n contenida en ellas, ni su veracidad o licitud, ni de cualesquiera efectos que pudieran derivarse.</li>
<li>En todo caso, &ldquo;Soydechollos&rdquo; manifiesta que proceder&aacute; a la retirada inmediata de cualquier contenido que pudiera contravenir la legislaci&oacute;n nacional o internacional, la moral o el orden p&uacute;blico, procediendo a la retirada inmediata de la redirecci&oacute;n a dicho sitio web, poniendo en conocimiento de las autoridades competentes el contenido en cuesti&oacute;n.</li>
<li>Los precios indicados en la web, de haberlos, ser&aacute;n v&aacute;lidos salvo error tipogr&aacute;fico, y susceptibles de cambios sin previo aviso, puesto que &laquo;Soydechollos&raquo; no tiene control sobre la informaci&oacute;n de las tiendas enlazadas, las cuales var&iacute;an los precios continuamente, sobre todo en este tipo de ofertas tan agresivas que se comparten.</li>
<li>&ldquo;Soydechollos&rdquo; ofrece sus servicios de manera indefinida, pudiendo, no obstante, suspender la prestaci&oacute;n de los mismos, unilateralmente y sin previo aviso.</li>
<li>&ldquo;Soydechollos&rdquo; no se har&aacute; responsable de los da&ntilde;os y perjuicios, propios o a terceros, producidos por un mal uso de esta web por parte del Usuario.</li>
<li>Como Usuario, te comprometes a no utilizar el Sitio Web, ni sus contenidos, productos y/o servicios, para la realizaci&oacute;n de actividades contrarias a la Ley, a la moral, a las buenas costumbres o al orden p&uacute;blico y, con fines o efectos il&iacute;citos, prohibidos o lesivos de derechos e intereses de terceros.</li>
<li>No podr&aacute;s utilizar esta Web con fines il&iacute;citos o lesivos o que puedan impedir el normal funcionamiento de la misma.</li>
<li>Te comprometes a no&nbsp;obstaculizar el acceso de otros usuarios al servicio mediante el consumo masivo de los recursos inform&aacute;ticos a trav&eacute;s de los cuales el titular del Sitio Web presta el servicio, as&iacute; como realizar acciones que da&ntilde;en, interrumpan o generen errores en dichos sistemas.</li>
<li>No podr&aacute;s difundir&nbsp;contenidos o propaganda de car&aacute;cter racista, xen&oacute;fobo, pornogr&aacute;fico-ilegal, de apolog&iacute;a del terrorismo o atentatorio contra los derechos humanos.</li>
<li>Te obligas a no falsear tu identidad haci&eacute;ndote pasar por otra persona.</li>
<li>Respectar&aacute;s la propiedad intelectual de todo el contenido de esta Web, por lo que no podr&aacute;s reproducirlo, distribuirlo o modificarlo, total o parcialmente, sin contar con la autorizaci&oacute;n expresa de &laquo;Soydechollos&raquo;.</li>
</ol>
<p>&laquo;Soydechollos&raquo; se reserva el derecho a denegar o retirar el acceso a la Web y/o los servicios ofrecidos sin necesidad de preaviso, a instancia propia o de un tercero, a aquellos usuarios que incumplan las presentes Condiciones de Uso.</p>
<p><strong>2.3. Marco normativo</strong></p>
<p>La actividad de esta web se encuentra sujeta al marco legal espa&ntilde;ol y europeo, concretamente a las siguientes normas:</p>
<ul>
<li>Reglamento General de Protecci&oacute;n de Datos (RGPD) (UE) 2016/679, que regula el tratamiento de datos personales en los pa&iacute;ses de la Uni&oacute;n Europea.</li>
<li>Ley Org&aacute;nica 3/2018, de 5 de diciembre, sobre protecci&oacute;n de datos y derechos digitales (LOPD y GDD), normas de &aacute;mbito regional (aplicables a Espa&ntilde;a), y que definen y ampl&iacute;an muchos de los conceptos y derechos presentes en el RGPD.</li>
<li>Ley 34/2002, de 11 de julio, de Servicios de la Sociedad de la Informaci&oacute;n y del Comercio Electr&oacute;nico (LSSICE), norma que afecta a aquellas webs que, de alguna forma, realicen actividades econ&oacute;micas mediante medios electr&oacute;nicos, como es el caso de esta web.</li>
</ul>
<p><strong>3. PROPIEDAD INTELECTUAL E INDUSTRIAL</strong></p>
<p>El Sitio Web, incluyendo a t&iacute;tulo enunciativo pero no limitativo su programaci&oacute;n, edici&oacute;n, compilaci&oacute;n y dem&aacute;s elementos necesarios para su funcionamiento, los dise&ntilde;os, logotipos, texto y/o gr&aacute;ficos son propiedad de &laquo;Soydechollos&raquo; o en su caso dispone de licencia o autorizaci&oacute;n expresa por parte de los autores.</p>
<p>Independientemente de la finalidad para la que fueran destinados, la reproducci&oacute;n total o parcial, uso, explotaci&oacute;n, distribuci&oacute;n y comercializaci&oacute;n, requiere en todo caso de la autorizaci&oacute;n previa por parte de &laquo;Soydechollos&raquo;. Cualquier uso no autorizado previamente ser&aacute; considerado un incumplimiento grave de los derechos de propiedad intelectual o industrial del autor.</p>
<p>Los dise&ntilde;os, logotipos, texto y/o gr&aacute;ficos ajenos a&nbsp;&laquo;Soydechollos&raquo; y que pudieran aparecer en el Sitio Web, pertenecen a sus respectivos propietarios, siendo ellos mismos responsables de cualquier posible controversia que pudiera suscitarse respecto a los mismos. En todo caso, el prestador cuenta con la autorizaci&oacute;n expresa y previa por parte de los mismos.</p>
<p>&ldquo;Soydechollos&rdquo; reconoce a favor de sus titulares los correspondientes derechos de propiedad industrial e intelectual, no implicando su sola menci&oacute;n o aparici&oacute;n en el sitio web la existencia de derechos o responsabilidad alguna del prestador sobre los mismos, como tampoco respaldo, patrocinio o recomendaci&oacute;n por parte del mismo.</p>
<p>Para realizar cualquier tipo de observaci&oacute;n respecto a posibles incumplimientos de los derechos de propiedad intelectual o industrial, as&iacute; como sobre cualquiera de los contenidos del Sitio Web, puede hacerlo a trav&eacute;s del&nbsp;<a href="https://soydechollos.com/contacto/">formulario de contacto</a>.</p>
<p><strong>4. POL&Iacute;TICA DE ENLACES Y PUBLICIDAD</strong></p>
<p><strong>4.1. Enlaces mostrados en el sitio web</strong></p>
<p>&laquo;Soydechollos&raquo; utiliza enlaces de recomendaci&oacute;n o afiliaci&oacute;n de productos y servicios de marcas que hayan establecido un programa de afiliados. Estos enlaces se usan despu&eacute;s de haber probado dichos productos y servicios, o bien, haber realizado pruebas o investigaci&oacute;n que permitan valorar que cumplen con un adecuado nivel de calidad.</p>
<p>Todos los enlaces mostrados en la Web son dirigidos a sitios o tiendas de confianza, que han sido probados o investigados y que &laquo;Soydechollos&raquo; recomienda a t&iacute;tulo personal. No obstante,&nbsp;en ning&uacute;n caso &laquo;Soydechollos&raquo; se hace responsable de los resultados que se deriven por el acceso a dichos enlaces.</p>
<p><strong>4.2. Enlaces externos hacia nuestro sitio web</strong></p>
<p>Est&aacute; permitido que se hagan enlaces al Sitio Web https://soydechollos.com/ siempre que no se establezca ninguna manifestaci&oacute;n falsa, inexacta o incorrecta sobre la misma. El establecimiento del enlace no implica la existencia de relaciones entre &laquo;Soydechollos&raquo; y el titular de la web desde el cual se realice, ni el conocimiento y aceptaci&oacute;n de &laquo;Soydechollos&raquo; de los servicios y contenidos ofrecidos en dicha web.</p>
<p><strong>4.3. Publicidad mostrada en el sitio web</strong></p>
<p>La informaci&oacute;n que aparece en los anuncios insertados, son facilitados por los propios anunciantes, por lo que &laquo;Soydechollos&raquo; no se hace responsable de posibles inexactitudes o errores que pudieran contener los anuncios, ni garantiza en modo alguno la experiencia, integridad o responsabilidad de los anunciantes o la calidad de sus productos y/o servicios.</p>
<p>Adem&aacute;s, los anuncios permanecer&aacute;n publicados en el portal hasta que sean eliminados o suspendidos por parte del anunciante o de &laquo;Soydechollos&raquo;, que l&oacute;gicamente no es responsable de que, una vez dados de baja en sus bases de datos, los anuncios contin&uacute;en siendo indexados en buscadores ajenos a este portal.</p>
<p>Debes entender que cualquier relaci&oacute;n contractual o extracontractual que t&uacute;, como Usuario, formalices con los anunciantes, afiliados o terceras personas contactadas a trav&eacute;s de este blog se entienden realizados &uacute;nica y exclusivamente entre el Usuario y el anunciante y/o tercera persona. As&iacute; que debes aceptar que &laquo;Soydechollos&raquo; &uacute;nicamente act&uacute;a como cauce o medio publicitario y que por tanto no tiene ning&uacute;n tipo de responsabilidad sobre los da&ntilde;os o perjuicios de cualquier naturaleza ocasionados con motivo de sus negociaciones, conversaciones y/o relaciones contractuales o extracontractuales con los anunciantes o terceras personas f&iacute;sicas o jur&iacute;dicas contactadas a trav&eacute;s de este sitio web.</p>
<p>Por ello, &laquo;Soydechollos&raquo; no garantiza, ni se hace responsable de la licitud, fiabilidad, utilidad, veracidad y actualidad de los contenidos de estos sitios web de terceros o de sus pr&aacute;cticas de privacidad. Por favor, antes de proporcionar tu informaci&oacute;n personal a estos sitios web ajenos a &laquo;Soydechollos&raquo;, ten en cuenta que sus pr&aacute;cticas de privacidad pueden diferir de las nuestras.</p>
<p><strong>5. PROTECCI&Oacute;N DE DATOS</strong></p>
<p>&ldquo;Soydechollos&rdquo; se encuentra profundamente comprometido con el cumplimiento de la normativa espa&ntilde;ola de protecci&oacute;n de datos de car&aacute;cter personal, y garantiza el cumplimiento &iacute;ntegro de las obligaciones dispuestas, as&iacute; como la implementaci&oacute;n de las medidas de seguridad dispuestas en la Ley Org&aacute;nica 3/2018, de 5 de diciembre, sobre protecci&oacute;n de datos y derechos digitales (LOPD y GDD), as&iacute; como para el cumplimiento del Reglamento General de Protecci&oacute;n de Datos (RGPD) (UE) 2016/679.</p>
<p>De conformidad con estas normativas, informamos que es posible que se nos faciliten ciertos datos personales a trav&eacute;s de formularios de registro o contacto, o mediante el env&iacute;o de emails, y que &eacute;stos ser&aacute;n objeto de tratamiento por &ldquo;Soydechollos&rdquo;. El env&iacute;o de estos datos personales constituye el consentimiento expreso al tratamiento de los mismos, si bien este consentimiento es de car&aacute;cter revocable. M&aacute;s informaci&oacute;n en nuestra&nbsp;<a href="https://soydechollos.com/politica-privacidad/">Pol&iacute;tica de Privacidad</a>.</p>
<p><strong>6. EXCLUSI&Oacute;N DE GARANT&Iacute;AS Y RESPONSABILIDAD</strong></p>
<p>Este Sitio Web ha sido revisado y probado para que funcione correctamente. En principio, puede garantizarse el correcto funcionamiento los 365 d&iacute;as del a&ntilde;o, 24 horas al d&iacute;a. No obstante, no se descarta la posibilidad de que existan ciertos errores del servidor web, fallo de la base de datos, tareas de programaci&oacute;n o circunstancias semejantes, o que acontezcan causas de fuerza mayor, que hagan imposible el acceso a la p&aacute;gina web.</p>
<p>&laquo;Soydechollos&raquo; tampoco se responsabiliza o garantiza que el contenido o software al que pueda accederse a trav&eacute;s de este sitio Web, est&eacute; libre de error o cause un da&ntilde;o al sistema inform&aacute;tico (software y hardware) del Usuario. En ning&uacute;n caso &ldquo;Soydechollos&rdquo; ser&aacute; responsable por las p&eacute;rdidas, da&ntilde;os o perjuicios de cualquier tipo que surjan por el acceso, navegaci&oacute;n y el uso del Sitio Web, incluy&eacute;ndose, pero no limit&aacute;ndose, a los ocasionados a los sistemas inform&aacute;ticos o los provocados por la introducci&oacute;n de virus.</p>
<p>&ldquo;Soydechollos&rdquo; tampoco se hace responsable de los da&ntilde;os que pudiesen ocasionarse a los usuarios por un uso inadecuado de este Sitio Web. En particular, no se hace responsable en modo alguno de las ca&iacute;das, interrupciones, falta o defecto de las telecomunicaciones que pudieran ocurrir.</p>
<p>Este Sitio Web no est&aacute; destinado a menores de edad, por lo que &ldquo;Soydechollos&rdquo; declina cualquier responsabilidad por el incumplimiento de este requisito.</p>
<p>El Sitio Web est&aacute; dirigido principalmente a usuarios residentes en Espa&ntilde;a.&nbsp;&ldquo;Soydechollos&rdquo; no asegura que el Sitio Web cumpla con legislaciones de otros pa&iacute;ses, ya sea total o parcialmente. Si el Usuario reside o tiene su domicilio en otro lugar y decide acceder y/o navegar en el Sitio Web lo har&aacute; bajo su propia responsabilidad, deber&aacute; asegurarse de que tal acceso y navegaci&oacute;n cumple con la legislaci&oacute;n local que le es aplicable, no asumiendo &ldquo;Soydechollos&rdquo; responsabilidad alguna que se pueda derivar de dicho acceso.</p>
<p><strong>7. EVENTOS, CONCURSOS Y ACTIVIDADES PROMOCIONALES</strong></p>
<p>&ldquo;Soydechollos&rdquo; o terceras empresas colaboradoras de &laquo;Soydechollos&raquo; podr&aacute;n organiza, a trav&eacute;s de diferentes plataformas, eventos, concursos y/o actividades promocionales de diversa &iacute;ndole.</p>
<p>En este sentido, la participaci&oacute;n en los posibles eventos, concursos o actividades promocionales ofrecidos por &ldquo;Soydechollos&rdquo;, implicar&aacute; la aceptaci&oacute;n, en su caso, de las condiciones particulares de cada uno de dichos eventos, concursos y/o actividades promocionales. Con car&aacute;cter general, la participaci&oacute;n en estos eventos, concursos y/o actividades promocionales puede estar sujeta a requisitos adicionales de los participantes (edad, lugar de domicilio, etc.), y la entrega de los premios a los ganadores puede encontrarse supeditada al cumplimiento de determinadas condiciones, que ser&aacute;n debidamente anunciadas.</p>
<p>Ser&aacute;n aplicables asimismo las siguientes condiciones generales de eventos, concursos y/ o actividades promocionales ofrecidos por &ldquo;Soydechollos&rdquo; o socios colaboradores, salvo que se opongan a lo detallado en las normas particulares aplicables en cada caso:</p>
<ol type="a">
<li>La participaci&oacute;n en los eventos, concursos y/o actividades promocionales ofrecidas por&nbsp;&ldquo;Soydechollos&rdquo; es personal, no admiti&eacute;ndose la participaci&oacute;n a trav&eacute;s de terceros, incluyendo agencias.</li>
<li>Perfiles falsos o cuentas destinadas a participar en sorteos de forma masiva ser&aacute;n excluidos.</li>
<li>Los menores de 18 a&ntilde;os no podr&aacute;n participar en los eventos, concursos y/o actividades promocionales ofrecidas por &ldquo;Soydechollos&rdquo;.</li>
<li>La participaci&oacute;n de personas jur&iacute;dicas est&aacute; expresamente excluida.</li>
<li>Los empleados de &ldquo;Soydechollos&rdquo; o sus familiares directos, o de cualquier patrocinador y/o empresa colaboradora en la organizaci&oacute;n del evento, concurso y/o actividad promocional, no podr&aacute;n tomar parte en el evento, concurso y/o actividad promocional.</li>
<li>&ldquo;Soydechollos&rdquo; podr&aacute; finalizar de forma anticipada y/o extender el evento, concurso o actividad promocional en caso de que fuera razonable o necesario.</li>
<li>En el caso de que &ldquo;Soydechollos&rdquo; detecte cualquier anomal&iacute;a o actuaci&oacute;n fraudulenta o sospeche que un participante est&aacute; tratando de impedir el normal desarrollo de un evento, concurso o actividad promocional, podr&aacute; de forma unilateral y sin necesidad de previo aviso, eliminar la inscripci&oacute;n de ese participante, as&iacute; como retirar el evento, concurso o actividad promocional, y/o declararlo desierto, sin que &ldquo;Soydechollos&rdquo; incurra en responsabilidad alguna frente a los participantes.</li>
<li>Los premios ser&aacute;n personales e intransferibles. Ning&uacute;n premio podr&aacute; cambiarse por otros bienes o servicios o entregarse en efectivo. En caso de que fuera necesario, &ldquo;Soydechollos&rdquo; se reserva el derecho de sustituir los premios por otros de valor equivalente.</li>
<li>El ganador del evento, concurso o actividad promocional que reciba un premio ser&aacute; responsable de los impuestos aplicables y de cualesquiera gastos que no figuren detallados en la descripci&oacute;n del premio.</li>
<li>En ning&uacute;n caso &ldquo;Soydechollos&rdquo; responder&aacute; de los eventuales da&ntilde;os y perjuicios sufridos por el ganador o terceros en relaci&oacute;n con el premio o la participaci&oacute;n en el evento, concurso o promoci&oacute;n de que se trate, a salvo de las irrenunciables por ley.</li>
<li>Los sorteos realizados a trav&eacute;s de la&nbsp;<a href="https://gleam.io/" target="_blank" rel="nofollow">plataforma Gleam</a>&nbsp;quedar&aacute;n sometidos a la&nbsp;<a href="https://gleam.io/privacy" target="_blank" rel="nofollow">pol&iacute;tica de privacidad de dicha plataforma</a>. Los datos de usuarios almacenados en esta plataforma tienen como objetivo la gesti&oacute;n del sorteo y el contacto con el ganador.</li>
<li>Los participantes ceden a &ldquo;Soydechollos&rdquo; todos los derechos de explotaci&oacute;n de propiedad intelectual e industrial, as&iacute; como cualesquiera otros derechos, incluidos los de imagen, sobre los comentarios, fotograf&iacute;as, v&iacute;deos o cualquier otro contenido y/o material que en su caso entreguen a &ldquo;Soydechollos&rdquo; o publiquen para su participaci&oacute;n en el evento, concurso o actividad promocional y aceptan su utilizaci&oacute;n por parte de &ldquo;Soydechollos&rdquo;. En el supuesto que los derechos sobre las fotograf&iacute;as, v&iacute;deos o cualquier otro contenido y/ o materiales pertenezcan a un tercero, el participante deber&aacute; obtener autorizaci&oacute;n del tercero titular de los derechos antes de entregar a &ldquo;Soydechollos&rdquo; o publicar la fotograf&iacute;a, v&iacute;deo o contenido y/o material de que se trate.</li>
<li>&ldquo;Soydechollos&rdquo; podr&aacute; suspender o cancelar cualquier evento, concurso y/o actividad promocional por motivos de fuerza mayor.</li>
<li>La participaci&oacute;n en cualquiera de nuestros eventos, concursos y/o actividades promocionales supone la renuncia expresa a cualquier otro fuero que pudiere corresponderte, aceptando los juzgados y tribunales de Pontevedra como competentes para dilucidar cualquier reclamaci&oacute;n.</li>
<li>La participaci&oacute;n en cualquiera de nuestros concursos o promociones supone la plena aceptaci&oacute;n de estas condiciones generales de eventos, concursos y/o actividades promocionales, de las Condiciones de Uso, as&iacute; como las condiciones particulares aplicables en cada caso.</li>
</ol>
<p>En todo caso, en eventos, concursos y/o actividades promocionales organizados por terceras empresas colaboradoras de &laquo;Soydechollos&raquo;, deber&aacute;s dirigirte directamente a dichas empresas en caso de posibles reclamaciones, no siendo &ldquo;Soydechollos&rdquo; responsable, directo o indirecto, en caso de cualquier fallo, error o, en general, incumplimiento de dichas empresas colaboradoras respecto de los eventos, concursos, y/o cualesquiera actividades promocionales organizadas por las mismas, siendo &eacute;stas empresas las exclusivas responsables.</p>
<p><strong>8. POL&Iacute;TICA ANTI-SPAM</strong></p>
<p>&ldquo;Soydechollos&rdquo; se declara completamente en contra del env&iacute;o de comunicaciones comerciales no solicitadas y a cualquier tipo de conducta o manifestaci&oacute;n conocida como &ldquo;spam&rdquo;. Asimismo, se declara comprometido con la lucha contra este tipo de pr&aacute;cticas abusivas.</p>
<p>Por tanto, &ldquo;Soydechollos&rdquo; garantiza al Usuario a que bajo ning&uacute;n concepto los datos personales recogidos en el sitio web ser&aacute;n cedidos, compartidos, transferidos, ni vendidos a ning&uacute;n tercero.</p>
<p>Por las mismas razones, el proceso de registro no debe ser utilizado para inscribir direcciones de correo de personas ajenas sin el consentimiento expreso de las personas afectadas. &ldquo;Soydechollos&rdquo; implementa como contramedida a esta pr&aacute;cticas una lista de correo de tipo double opt-in que necesita la confirmaci&oacute;n expl&iacute;cita por parte del titular de la cuenta de correo electr&oacute;nico indicada como direcci&oacute;n de suscripci&oacute;n, antes de recibir comunicaciones por correo electr&oacute;nico.</p>
<p>En el caso de que aun as&iacute; un Usuario reciba comunicaciones de este sitio web sin haberse registrado, o sin haber dado su consentimiento expreso a dicho registro, puede cancelar la suscripci&oacute;n desde los enlaces que se proporcionan en la propia comunicaci&oacute;n.</p>
<p>Asimismo, &ldquo;Soydechollos&rdquo; se compromete a no realizar publicidad enga&ntilde;osa ni recomendar productos o servicios que no valorar&iacute;amos a t&iacute;tulo personal. A estos efectos, por lo tanto, no ser&aacute;n considerados como publicidad enga&ntilde;osa los errores formales o num&eacute;ricos que puedan encontrarse a lo largo del contenido de las distintas secciones del sitio web, producidos como consecuencia de un mantenimiento y/o actualizaci&oacute;n incompleta o defectuosa de la informaci&oacute;n contenida en estas secciones. &ldquo;Soydechollos&rdquo; como consecuencia de lo dispuesto en este apartado, se compromete a corregirlo tan pronto como tenga conocimiento de dichos errores.</p>
<p><strong>9. LEY APLICABLE Y JURISDICCI&Oacute;N</strong></p>
<p>Las presentes Condiciones de Uso del sitio web se rigen en todos y cada uno de sus extremos por la ley espa&ntilde;ola. El idioma de redacci&oacute;n e interpretaci&oacute;n de este aviso legal es el espa&ntilde;ol. Para la resoluci&oacute;n de todas las controversias o cuestiones relacionadas con el presente sitio web o de las actividades en &eacute;l desarrolladas, ser&aacute; de aplicaci&oacute;n la legislaci&oacute;n espa&ntilde;ola, a la que se someten expresamente las partes, siendo competentes para la resoluci&oacute;n de todos los conflictos derivados o relacionados con su uso los Juzgados y Tribunales de Pontevedra.</p>  
    </div>
</div>