<div class="container py-20">
<h1 class="font-28 color-blue2">POLÍTICA DE PRIVACIDAD</h1>

    <div class="bg-white rounded p-20">
    	<div class="entry-content">
<p style="text-align: center;"><em>Documento revisado el 29/10/2019</em></p>
<p>“Soydechollos” informa a los usuarios del sitio web sobre su política respecto del tratamiento y protección de los datos de carácter personal de los usuarios y clientes que puedan ser recabados por la navegación, adquisición de productos o contratación de servicios a través de su sitio web. En este sentido, “Soydechollos” garantiza el cumplimiento de la normativa vigente en materia de protección de datos personales, reflejada en&nbsp;Reglamento General de Protección de Datos (RGPD) (UE) 2016/679 y en Ley Orgánica 3/2018, de 5 de diciembre, sobre protección de datos y derechos digitales (LOPD y GDD).</p>
<p>De conformidad con estas normativas, informamos que la utilización de nuestra web puede requerir que se faciliten ciertos datos personales a través de formularios de contacto, o mediante el envío de emails, y que éstos serán objeto de tratamiento por “<strong>Soydechollos”</strong>, Responsable del tratamiento, cuyos datos son: Aitor Rosales Núñez, con domicilio a estos efectos en Rúa Coruña 76 9ºD, Vigo (España) con NIF: 53191490B. Teléfono de contacto: 625293513. Correo electrónico de contacto: contacto[arroba]soydechollos.com</p>
<p>En el tratamiento de los datos personales de los usuarios se aplicarán los siguientes principios que se ajustan a las exigencias del nuevo reglamento europeo de protección de datos:</p>
<ul>
<li><strong>Principio de licitud, lealtad y transparencia</strong>: siempre se va a requerir el consentimiento para el tratamiento de los datos personales para uno o varios fines específicos que se informará previamente con absoluta transparencia.</li>
<li><strong>Principio de minimización de datos</strong>: solo se van a solicitar datos estrictamente necesarios en relación con los fines para los que se necesitan. Por ejemplo, para la newsletter sólo necesitamos un correo y nombre.</li>
<li><strong>Principio de limitación del plazo de conservación</strong>: los datos serán mantenidos durante no más tiempo del necesario para los fines del tratamiento, en función a la finalidad.</li>
<li><strong>Principio de integridad y confidencialidad</strong>: los datos serán tratados de tal manera que se garantice una seguridad adecuada de los datos personales y se garantice confidencialidad. Debes saber que «Soydechollos»toma todas las precauciones necesarias para evitar el acceso no autorizado o uso indebido de los datos de sus usuarios por parte de terceros.</li>
</ul>
<p><strong>1. MEDIDAS DE SEGURIDAD</strong></p>
<p>En cumplimiento de la legislación vigente en materia de protección de datos, se informa a los usuarios de que, en “Soydechollos”, se&nbsp;han adoptado las medidas técnicas y organizativas conforme a lo dispuesto en la citada normativa. Los datos personales que se recogen en los formularios son objeto de tratamiento, únicamente,&nbsp;por parte del personal de “Soydechollos” o de los Encargados del Tratamiento aquí establecidos. Se han adoptado las medidas de seguridad adecuadas a los datos que se facilitan y, además, se han instalado todos los medios y medidas técnicas a su alcance para evitar la pérdida, mal uso, alteración, acceso no autorizado y robo de los datos que nos facilitan.</p>
<p>El Sitio Web de “Soydechollos” cuenta con un cifrado SSL, que permite al Usuario el envío seguro de sus datos personales a través de los formularios de contacto o de registro en la newsletter del sitio web.</p>
<p><strong>2. VERACIDAD DE LOS DATOS</strong></p>
<p>El Cliente o Usuario manifiesta que todos los datos facilitados por él son ciertos y correctos y se compromete a mantenerlos actualizados, comunicando, a “Soydechollos”, cualquier modificación de los mismos. El usuario responderá de la veracidad de sus datos y será el único responsable de cuantos conflictos o litigios pudieran resultar por la falsedad de los mismos. Es importante que, para que podamos mantener los datos personales actualizados, el usuario informe a “Soydechollos” siempre que haya habido alguna modificación en los mismos. En caso contrario, no podemos responder de su veracidad.</p>
<p><strong>3. EJERCICIO DE DERECHOS</strong></p>
<p>La LOPD y el RGPD concede a los interesados la posibilidad de ejercer una serie de derechos relacionados con el tratamiento de sus datos personales. En tanto en cuanto los datos del usuario son objeto de tratamiento por parte de “Soydechollos”, éstos podrán ejercer sus derechos. Para ello, el usuario deberá dirigirse, aportando documentación que acredite su identidad (DNI o pasaporte), mediante correo electrónico a contacto(arroba)soydechollos.com, o bien mediante comunicación escrita a la dirección que aparece en nuestro <a href="https://soydechollos.com/aviso-legal/">aviso legal</a>. Dicha comunicación deberá reflejar la siguiente información: Nombre y apellidos del usuario, la petición de solicitud, el domicilio y los datos acreditativos.</p>
<p>El ejercicio de derechos deberá ser realizado por el propio usuario. No obstante, podrán ser ejecutados por una persona autorizada como representante legal del autorizado. En tal caso, se deberá aportar la documentación que acredite esta representación del interesado.</p>
<p>El usuario podrá solicitar el ejercicio de los derechos siguientes:</p>
<ul>
<li>Derecho a solicitar el <strong>acceso</strong> a los datos personales.</li>
<li>Derecho a solicitar su<strong> rectificación</strong> (en caso de que sean incorrectos) o supresión.</li>
<li>Derecho a solicitar la <strong>limitación</strong> de su tratamiento, en cuyo caso únicamente serán conservados por “Soydechollos” para el ejercicio o la defensa de reclamaciones.</li>
<li>Derecho a<strong> oponerse</strong> al tratamiento: “Soydechollos” dejará de tratar sus datos, salvo que por motivos legítimos o el ejercicio o la defensa de posibles reclamaciones se tengan que seguir tratando.</li>
<li>Derecho a la <strong>portabilidad</strong> de los datos: en caso de que quiera que sus datos sean tratados por otra firma, ”Soydechollos” le facilitará la portabilidad de sus datos al nuevo responsable.</li>
</ul>
<p>En el caso de que se haya otorgado el consentimiento para alguna finalidad específica, <strong>el usuario tiene derecho a retirar el consentimiento en cualquier momento</strong>, sin que ello afecte a la licitud del tratamiento basado en el consentimiento previo a su retirada.</p>
<p>Si un usuario considera que hay un problema con la forma en que “Soydechollos” está manejando sus datos, puede dirigir sus reclamaciones por email a «contacto(arroba)soydechollos.com» o a la autoridad de protección de datos que corresponda, siendo la Agencia Española de Protección de Datos la indicada en el caso de España.</p>
<p>Además, “Soydechollos” ha elaborado una guía detallada para que el Usuario pueda dar de baja cualquiera suscripción activa que se puede consultar en el siguiente enlace: https://soydechollos.com/baja/</p>
<p><strong>4. CONSERVACIÓN DE LOS DATOS</strong></p>
<p>Los datos desagregados serán conservados sin plazo de supresión. En cuanto a los datos de Clientes, el período de conservación de los datos personales variará en función del servicio que el Cliente contrate. En cualquier caso, será el mínimo necesario, pudiendo mantenerse hasta:</p>
<ul>
<li>4 años: Ley sobre Infracciones y Sanciones en el Orden Social (obligaciones en materia de afiliación, altas, bajas, cotización, pago de salarios…); Arts. 66 y sig. Ley General Tributaria (libros de contabilidad…)</li>
<li>5 años: Art. 1964 Código Civil (acciones personales sin plazo especial)</li>
<li>6 años: Art. 30 Código de Comercio (libros de contabilidad, facturas…)</li>
<li>10 años: Art. 25 Ley de Prevención del Blanqueo de Capitales y Financiación del Terrorismo.</li>
<li>Sin plazo: datos desagregados y anonimizados.</li>
</ul>
<p>Los usuarios de listas de correo o los subidos por “Soydechollos” a páginas o perfiles de RRSS, se conservarán hasta que el usuario retire el consentimiento.</p>
<p>Datos de candidatos (C.V.), de haberlos: En caso de que el candidato no sea seleccionado, “Soydechollos” podrá mantener almacenado su currículo un máximo de dos años para incorporarlo a futuras convocatorias, a menos que el candidato se manifieste en contrario.</p>
<p><strong>5. OBTENCIÓN Y TRATAMIENTO DE DATOS</strong></p>
<p>“Soydechollos” tiene el deber de informar a los usuarios de su sitio web acerca de la recogida de datos de carácter personal que pueden llevarse a cabo en el sitio web. En este sentido, “Soydechollos” será considerado como Responsable de los datos recabados mediante los medios descritos. Los datos recogidos por el Sitio Web son datos básicos meramente identificativos, <strong>no se tratan categorías de datos especialmente protegidos</strong>.</p>
<p>Tal y como establece la LSSICE, “Soydechollos” se compromete a no remitir comunicaciones comerciales sin identificarlas como tales. A estos efectos, no será considerada como comunicación comercial la información enviada a los clientes para el mantenimiento de la relación contractual existente.</p>
<p>En cualquier caso, se obtendrán únicamente los datos precisos para poder realizar el servicio contratado, o para poder responder adecuadamente a la petición de información realizada por el usuario.</p>
<p>En ocasiones, los datos personales se proporcionarán a través de enlaces a sitios web de terceros. En este caso,&nbsp;en ningún momento el personal de “Soydechollos” tendrá acceso a los datos personales que el Cliente facilite a dichos terceros.</p>
<p>Además, a través de las cookies y tecnologías similares podemos&nbsp;mejorar y personalizar tu experiencia de navegación, realizar analíticas e investigación, proporcionar funciones de redes sociales, o llevar un seguimiento de las ventas (en sitios web de terceros) producidas a través de nuestros enlaces de tracking.</p>
<p>Las operaciones, gestiones y procedimientos técnicos que se realicen de forma automatizada o no automatizada y que posibiliten la recogida, el almacenamiento, la modificación, la transferencia y otras acciones sobre datos de carácter personal, tienen la consideración de Tratamiento de datos personales.</p>
<p><strong>5.1 Cómo Soydechollos recaba información del Usuario y/o Cliente</strong></p>
<ul>
<li>Formularios de contacto/email. Finalidad: Dar contestación a su solicitud de información realizada a través de nuestro/s formulario/s de contacto. Legitimación: La base jurídica que legitima este tratamiento es el consentimiento del Usuario, que podrá revocar en cualquier momento. Cesión de datos: Los datos personales serán tratados a través de servidores gestionados por <a href="https://www.ovh.es/" target="_blank" rel="nofollow">OVH</a>, que tendrá la consideración de Encargado del Tratamiento.</li>
<li>Formularios de alta en lista de correo (newsletter). Finalidad: Envío de comunicaciones electrónicas de interés para el Usuario, tales como: boletines (newsletters) o nuevas entradas (posts). Legitimación: La base jurídica que legitima este tratamiento es el consentimiento del Usuario, que podrá revocar en cualquier momento. Cesión de datos: Los datos personales serán tratados a través de servidores gestionados por Mailchimp, que tendrá la consideración de Encargado del Tratamiento.</li>
<li>En caso de que contactes con nosotros, podremos guardar una copia de dicha correspondencia.</li>
<li>Si participas en alguno de nuestros sorteos o campañas, podremos guardar una copia de los datos que nos proporciones.</li>
<li>También podremos pedirte que rellenes encuestas con propósitos de investigación, si bien tu colaboración y respuesta a las mismas siempre será opcional.</li>
<li>Formulario de comentarios: la web incluye un formulario para comentar posts gestionado a través del servicio externo Disqus. El usuario podrá publicar comentarios registrándose en Disqus o bien como invitado sin necesidad de introducir ningún dato personal.</li>
<li>Datos no identificativos de navegación: Cuando el usuario se registra o navega en esta web, se almacenan “cookies”. El usuario puede consultar en cualquier momento la <a href="https://soydechollos.com/politica-cookies/">política de cookies</a> para ampliar información sobre el uso de cookies y como desactivarlas.</li>
<li>Dado que nos financiamos a través de comisiones, podemos recibir información sobre las compras en línea (es decir, el valor de los pedidos) que puedes realizar en sitios web de terceros (por ejemplo, Amazon) después de una visita a nuestro Sitio Web. Dicha información se nos transmite automáticamente con la ayuda de cookies de seguimiento. Nunca recibimos información que pueda identificar al Usuario directamente, sino simplemente información relacionada con la comisión, como el valor de su compra y la fecha y hora de la transacción. También trabajamos con las llamadas redes de afiliados, que nos conectan con los comerciantes y se hacen cargo del proceso técnico y de facturación. En estos casos, recibimos la información correspondiente de dichas redes. Sólo utilizamos esta información a efectos de facturación.</li>
</ul>
<p><strong>5.2 Qué datos podemos recopilar</strong></p>
<p>La información recopilada a través de formularios, cookies u otros mecanismos descritos, puede incluir:</p>
<ul>
<li>Nombre</li>
<li>Email</li>
<li>Dirección postal (en caso de ganadores de sorteos por ejemplo)</li>
<li>Nombre de usuario o alias de la Red Social (participación en sorteos)</li>
<li>Qué página de Soydechollos.com es visitada</li>
<li>Java activado/desactivado</li>
<li>Cookies activadas/desactivadas</li>
<li>Dirección IP abreviada</li>
<li>URL remitente (es decir, el sitio visitado anteriormente)</li>
<li>Sistema operativo</li>
<li>Navegador</li>
<li>Fecha y hora de la visita</li>
<li>Su actividad de navegación (como posiciones de desplazamiento, clics y movimientos del ratón)</li>
<li>Tiempo y duración de las interacciones en las páginas</li>
<li>Búsquedas realizadas</li>
<li>Clics en banners y enlaces</li>
<li>Otra información sobre cómo interactuó con este sitio web</li>
</ul>
<p><strong>5.3 Quién trata los datos facilitados a Soydechollos</strong></p>
<ul>
<li>Los datos recogidos en el Sitio Web serán tratados a través de servidores (hosting) gestionados por <strong>OVH HISPANO, S.L.U</strong>., con&nbsp;CIF B83834747 y domicilio social en C/ Alcalá 21, 5ª planta, 28014 Madrid (España), que también es una de las empresas prestadoras de servicios de correo electrónico, y, que tendrá la consideración de Encargado del Tratamiento. Se puede consultar la política de privacidad y demás aspectos legales de dicha compañía en su <a href="https://www.ovh.es/soporte/documentos_legales/" target="_blank" rel="nofollow">página Web</a>.</li>
<li><strong>CB Aragonesa Gestión Administrativa S.L.</strong>, con domicilio en C/San Antonio María Claret, 55, local, trata los datos de clientes y socios de «Soydechollos» con la finalidad de realizar sus servicios de asesoría/gestoría.</li>
<li>Por su parte, los datos de correo y nombre recogido en formularios serán incorporados a una base de datos para el envío de comunicaciones comerciales y gestionar la suscripción a los servicios solicitados por el cliente o usuario, gestionada a través de los servidores de <strong>Mailchimp</strong>, que tendrá también la consideración de Encargado del Tratamiento. Podrá darse de baja en cualquier momento pulsando el enlace que encontrará en nuestras comunicaciones, o dirigiendo una solicitud de ejercicio de su derecho a “Soydechollos”.</li>
<li><strong>Google</strong> es nuestro prestador de servicios de correo electrónico, a través de los cuales se realizarán las comunicaciones (Gmail), y nuestros proveedor de análisis de datos y de publicidad.
<ul>
<li>Utilizamos Google Analitycs para analizar el uso que hacen los usuarios del blog. Para ello se utilizan cookies que son ficheros ubicados en tu equipo de acceso que almacenan información sobre tus hábitos de navegación, por ejemplo.&nbsp;La dirección IP es anonimizada, por lo que no será recopilada por Google. Cualquier identificador de usuario (por ejemplo, la identificación de cookies) almacenado por Google Analytics se eliminará automáticamente de los servidores de Google después de 50 meses.&nbsp;Si lo deseas puedes inhabilitar el seguimiento de Google Analytics mediante&nbsp;<a class="external" href="https://tools.google.com/dlpage/gaoptout" rel="nofollow" target="_blank">este complemento para el navegador ofrecido por Google</a>.</li>
<li>También utilizamos los servicios de Google Adsense&nbsp;para mostrar anuncios a los usuarios que acceden a esta web. El usuario puede utilizar la <a href="https://adssettings.google.com/authenticated?hl=es" target="_blank" rel="nofollow">configuración de anuncios</a> para administrar los anuncios de Google que quieres que se le muestren y los que no, basados en sus intereses. Aunque decida no recibir este tipo de anuncios, pueden seguir apareciendo en función de factores como su ubicación general derivada de la dirección IP, el tipo de navegador y las búsquedas recientes y anteriores relacionadas con su búsqueda actual. Se se desea obtener más información sobre esta práctica y conocer sus opciones para impedir que estas empresas usen esta información, <a href="https://www.google.es/policies/privacy" target="_blank" rel="nofollow">haz clic aquí</a>.</li>
</ul>
</li>
</ul>
<p><strong>6. REDES SOCIALES</strong></p>
<p>“Soydechollos” cuenta con perfil en las principales redes sociales de Internet (Facebook, Twitter, Google, Telegram), reconociéndose en todos los casos Responsable del tratamiento de los datos de sus seguidores, fans, suscriptores, comentaristas y otros perfiles de usuarios (en adelante, seguidores) publicados por “Soydechollos”. El tratamiento que “Soydechollos” llevará a cabo con dichos datos dentro de cada una de las referidas redes será el que la red social permita a los perfiles corporativos.</p>
<p>“Soydechollos” podrá informar a sus seguidores, cuando la ley no lo prohíba, por cualquier vía que la red social permita sobre sus actividades y ofertas, así como prestar servicio personalizado de atención al cliente. En ningún caso “Soydechollos” extraerá datos de las redes sociales, a menos que se obtuviera puntual y expresamente el consentimiento del usuario para ello (por ejemplo, para la realización de un concurso).</p>
<p>El usuario podrá acceder a las políticas de privacidad de cada Red Social, así como configurar su perfil para garantizar su privacidad. «Soydechollos» anima a los usuarios a familiarizarse con las condiciones de uso de las distintas redes sociales antes de comenzar a usarlas.</p>
<ul>
<li><a href="https://www.facebook.com/help/323540651073243" target="_blank" rel="nofollow">Facebook</a></li>
<li><a href="https://www.google.es/intl/es/policies/privacy/" target="_blank" rel="nofollow">Google</a></li>
<li><a href="https://twitter.com/privacy" target="_blank" rel="nofollow">Twitter</a></li>
<li><a href="https://telegram.org/privacy" target="_blank" rel="nofollow">Telegram</a></li>
</ul>
<p><strong>7. ENCARGADOS DEL TRATAMIENTO EN ESTADOS UNIDOS</strong></p>
<p>“Soydechollos” utiliza los servicios de suscripción por correo electrónico y envío de&nbsp;newsletters&nbsp;de la compañía norteamericana <strong>The Rocket Science Group, LLC</strong> (identificada por la marca comercial&nbsp;<strong>“</strong>MailChimp<strong>”</strong>). La suscripción al blog conlleva que los datos introducidos son transferidos a los servidores de la citada compañía, suponiendo una transferencia internacional de datos que el Usuario consiente de manera expresa con la aceptación de la presente política de privacidad.&nbsp;Mailchimp está acogido al acuerdo EU-US Privacy Shield, cuya información está disponible&nbsp;<a class="external" href="https://www.privacyshield.gov/list" target="blank" rel="nofollow noopener noreferrer">aquí</a>, aprobado por el Comité Europeo de Protección de Datos. Se puede consultar la política de privacidad y demás aspectos legales de dicha compañía en <a href="https://mailchimp.com/legal/" target="_blank" rel="nofollow">este enlace</a>.</p>
<p>“Soydechollos” cuenta con un sistema de gestión de comentarios que se realiza a través de <strong>Big Heads Labs Inc (</strong><strong>DISQUS, INC.)</strong>, un servicio externo que es ajeno a este sitio y tiene una política de privacidad y términos de uso propios, y que recomendamos revisar en los siguientes enlaces:&nbsp;<a href="https://help.disqus.com/customer/portal/articles/466259-privacy-policy" target="_blank" rel="nofollow noopener noreferrer">Política De Privacidad</a>&nbsp;y&nbsp;<a href="https://help.disqus.com/customer/portal/articles/466260-terms-of-service" target="_blank" rel="nofollow noopener noreferrer">Términos de Uso</a>. A&nbsp;estos efectos, «Soydechollos» se limita a poner a su disposición la funcionalidad pero, aunque los comentarios se vean incrustados en la Web, en realidad el Usuario está utilizando la plataforma de Disqus, por lo que es dicha compañía la que realiza el tratamiento de sus datos, en los términos que figuran en su política de privacidad. «Soydechollos» no es responsable de dicho tratamiento de datos por parte de Disqus, Inc. por lo que, si no está conforme con su política de privacidad, el Usuario debe abstenerse de incluir comentarios en la Web. Si quieres solicitar información sobre el tratamiento de tus datos deberás dirigirte a Disqus, Inc., 301 Howard St., Suite 300, San Francisco, CA 94105. Ademas, debes saber que Disqus está acogido al acuerdo EU-US Privacy Shield, cuya información está disponible&nbsp;<a class="external" href="https://www.privacyshield.gov/list" target="blank" rel="nofollow noopener noreferrer">aquí</a>, aprobado por el Comité Europeo de Protección de Datos.</p>
<p>“Soydechollos” también utiliza servicios de <a href="https://wordpress.org/" target="_blank" rel="nofollow">WordPress</a>&nbsp;(Automattic Inc) como proveedor de plataforma web. El&nbsp;servicio de correo electrónico de “Soydechollos” se presta usando los servicios de <a href="https://www.google.es/intl/es/about/" target="_blank" rel="nofollow">Google LLC</a> a través de Google Suite. Además, “Soydechollos” hace uso de las redes sociales estadounidenses Facebook y Twitter.</p>
<p>El usuario acepta expresamente y de forma inequívoca su consentimiento para el tratamiento de sus datos y para la transferencia internacional de los mismos a estas empresas prestadoras de servicios.</p>
<p><strong>8. COMUNICACIÓN DE INFORMACIÓN A TERCEROS</strong></p>
<p>“Soydechollos” <strong>no cederá, ni comunicará ni venderá a ningún tercero tus datos</strong>, excepto en los casos legalmente previstos o cuando la prestación de un servicio implique la necesidad de una relación contractual con un encargado de tratamiento, y siempre de acuerdo con las condiciones generales aprobadas por el usuario con anterioridad a la contratación del mismo. Por ejemplo, en caso de participar en un sorteo organizado por Soydechollos y otra compañía.</p>
<p>Así, al contratar nuestros servicios, el usuario acepta que alguno de los mismos puedan ser, total o parcialmente, subcontratados a otras personas o empresas, que tendrán la consideración de Encargados del Tratamiento, con los que se ha convenido el correspondiente contrato de confidencialidad, o adherido a sus políticas de privacidad, establecidas en sus respectivas páginas web. También acepta que algunos de los datos personales recabados sean facilitados a estos Encargados del Tratamiento, cuando sea necesario para la efectiva realización del servicio contratado. El usuario podrá negarse a la cesión de tus datos a los Encargados del Tratamiento, mediante petición escrita, por cualquiera de los medios anteriormente referenciados.</p>
<p><strong>9. CONFIDENCIALIDAD</strong></p>
<p>La información suministrada por el cliente tendrá, en todo caso, la consideración de confidencial, sin que pueda ser utilizada para otros fines que los relacionados con los servicios contratados o productos adquiridos a “Soydechollos”. “Soydechollos” se obliga a no divulgar ni revelar información sobre las pretensiones del cliente, los motivos del asesoramiento solicitado o la duración de su relación con este.</p>
<p><strong>10. VALIDEZ</strong></p>
<p>Esta política de privacidad y de protección de datos ha sido redactada por EXPERTOSLOPD®, <a href="https://www.expertoslopd.es" target="_blank" rel="nofollow">empresa de protección de datos</a>, a día 29 de Octubre de 2019, y podrá variar en función de los cambios de normativa y jurisprudencia que se vayan produciendo, siendo responsabilidad del titular de los datos la lectura del documento actualizado, en orden a conocer sus derechos y obligaciones al respecto en cada momento.</p>
</div>
    </div>
</div>